### ISSUE TITLE
Creating a release tag

### ISSUE THREAD

**Issue by KonstiDE** [jonas-haeusler/geojson-kotlin#1]
Hey, it would be cool if this repository had a release tag, like 1.0.0 so that it is possible to import the library via the git url for gradle as follows:

`com.github.jonas-haeusler:geojson-kotlin:1.0.0`

So far, for the people struggling with maven, just fork the repo and create a release yourself, worked for me :)

**Comment by jonas-haeusler** [comment]
hi @KonstiDE, whats wrong with the [artifact on Maven Central](https://central.sonatype.com/artifact/dev.haeusler.geojson-kotlin/geojson)? you should be able to just do a `implementation 'dev.haeusler.geojson-kotlin:geojson:1.0'` (or whatever your build system needs).

out of curiosity: how is a GitHub release resolvable as a Maven dependency? can you link me some documentation?

**Comment by KonstiDE** [comment]
I dont know and there probably nothing wrong with it, however, importing `implementation("dev.haeusler.geojson-kotlin:geojson:1.0")` it not working for me, he is missing the Moshi object for creating an adapter and along with adding a GeoJsonAdapter. Of course I set the `geojson-moshi` dependency in my build.gradle:

```gradle
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.6.20"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven { setUrl("https://jitpack.io") }
}

dependencies {
    testImplementation(kotlin("test"))

    implementation("com.squareup.okhttp3:okhttp:4.9.3")
    implementation("org.jsoup:jsoup:1.17.2")
    implementation("com.google.code.gson:gson:2.9.1")
    implementation("dev.haeusler.geojson-kotlin:geojson:1.0")
    implementation("dev.haeusler.geojson-kotlin:geojson-moshi:1.0")

}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```

Also `com.github.jonas-haeusler:geojson-kotlin:1.0.0` or at the moment an abitrary fork `com.github.jKonstiDE:geojson-kotlin:1.0.0` does the job in one go.

The git resolve is managed by [jitpack.io](https://github.com/jitpack/jitpack.io)

**Comment by jonas-haeusler** [comment]
thanks for the explanation, I think I now know what the problem is:

at some point, the Moshi dependency was not exposed to consumers of the geojson-moshi artifact. this was fixed with 3751dd2. however, this commit did not make it into the 1.0 release, making the Moshi dependency effectively a runtime-only dependency.

to work around this, you can, as you already did with the jitpack release, depend on the latest commit, or you can add the Moshi dependency explicitly as a compile time dependency to your Gradles dependency section. but as you are using Gson (at least in the excerpt above), it might be better to just write some adapters on your own, instead of having two json libraries on the classpath. if you do so, feel free to raise a merge request ;)

anyways, I'll try to release a new version within the next days which does contain the mentioned commit, so that the Moshi dependency is correctly exposed. i just have to remind myself how the release process worked...

thanks for letting me know about the issue!

**Comment by KonstiDE** [comment]
No worries, closing now :)

**Comment by jonas-haeusler** [comment]
[`geojson-moshi:1.1`](https://central.sonatype.com/artifact/dev.haeusler.geojson-kotlin/geojson-moshi/1.1) is now available on Maven Central, which brings Moshi as a compile-time dependency.
if you try it, let me know whether this worked for you.
